// JMDict 词性标签（英文）→ 中文映射。JMDict 词性为封闭集合（实测 83 个），
// 未覆盖的标签原样返回。词性在 dict_entries.pos 中按「、」连接多个标签。

const POS_ZH = {
  "'ku' adjective (archaic)": "ク形容词（古语）",
  "'shiku' adjective (archaic)": "シク形容词（古语）",
  "'taru' adjective": "タル形容词",
  "Godan verb - -aru special class": "五段动词（aru 特殊类）",
  "Godan verb - Iku/Yuku special class": "五段动词（iku/yuku 特殊类）",
  "Godan verb with 'bu' ending": "五段动词（bu 结尾）",
  "Godan verb with 'gu' ending": "五段动词（gu 结尾）",
  "Godan verb with 'ku' ending": "五段动词（ku 结尾）",
  "Godan verb with 'mu' ending": "五段动词（mu 结尾）",
  "Godan verb with 'nu' ending": "五段动词（nu 结尾）",
  "Godan verb with 'ru' ending": "五段动词（ru 结尾）",
  "Godan verb with 'ru' ending (irregular verb)": "五段动词（ru 结尾，不规则）",
  "Godan verb with 'su' ending": "五段动词（su 结尾）",
  "Godan verb with 'tsu' ending": "五段动词（tsu 结尾）",
  "Godan verb with 'u' ending": "五段动词（u 结尾）",
  "Godan verb with 'u' ending (special class)": "五段动词（u 结尾，特殊类）",
  "Ichidan verb": "一段动词",
  "Ichidan verb - kureru special class": "一段动词（kureru 特殊类）",
  "Ichidan verb - zuru verb (alternative form of -jiru verbs)": "一段动词（zuru 类，-jiru 动词的变体）",
  "Kuru verb - special class": "カ变动词",
  "Nidan verb (lower class) with 'dzu' ending (archaic)": "下二段动词（dzu 结尾，古语）",
  "Nidan verb (lower class) with 'gu' ending (archaic)": "下二段动词（gu 结尾，古语）",
  "Nidan verb (lower class) with 'hu/fu' ending (archaic)": "下二段动词（hu/fu 结尾，古语）",
  "Nidan verb (lower class) with 'ku' ending (archaic)": "下二段动词（ku 结尾，古语）",
  "Nidan verb (lower class) with 'mu' ending (archaic)": "下二段动词（mu 结尾，古语）",
  "Nidan verb (lower class) with 'nu' ending (archaic)": "下二段动词（nu 结尾，古语）",
  "Nidan verb (lower class) with 'ru' ending (archaic)": "下二段动词（ru 结尾，古语）",
  "Nidan verb (lower class) with 'su' ending (archaic)": "下二段动词（su 结尾，古语）",
  "Nidan verb (lower class) with 'tsu' ending (archaic)": "下二段动词（tsu 结尾，古语）",
  "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)": "下二段动词（u 结尾、we 活用，古语）",
  "Nidan verb (lower class) with 'yu' ending (archaic)": "下二段动词（yu 结尾，古语）",
  "Nidan verb (lower class) with 'zu' ending (archaic)": "下二段动词（zu 结尾，古语）",
  "Nidan verb (upper class) with 'bu' ending (archaic)": "上二段动词（bu 结尾，古语）",
  "Nidan verb (upper class) with 'gu' ending (archaic)": "上二段动词（gu 结尾，古语）",
  "Nidan verb (upper class) with 'hu/fu' ending (archaic)": "上二段动词（hu/fu 结尾，古语）",
  "Nidan verb (upper class) with 'ku' ending (archaic)": "上二段动词（ku 结尾，古语）",
  "Nidan verb (upper class) with 'ru' ending (archaic)": "上二段动词（ru 结尾，古语）",
  "Nidan verb (upper class) with 'tsu' ending (archaic)": "上二段动词（tsu 结尾，古语）",
  "Nidan verb (upper class) with 'yu' ending (archaic)": "上二段动词（yu 结尾，古语）",
  "Nidan verb with 'u' ending (archaic)": "二段动词（u 结尾，古语）",
  "Yodan verb with 'bu' ending (archaic)": "四段动词（bu 结尾，古语）",
  "Yodan verb with 'gu' ending (archaic)": "四段动词（gu 结尾，古语）",
  "Yodan verb with 'hu/fu' ending (archaic)": "四段动词（hu/fu 结尾，古语）",
  "Yodan verb with 'ku' ending (archaic)": "四段动词（ku 结尾，古语）",
  "Yodan verb with 'mu' ending (archaic)": "四段动词（mu 结尾，古语）",
  "Yodan verb with 'ru' ending (archaic)": "四段动词（ru 结尾，古语）",
  "Yodan verb with 'su' ending (archaic)": "四段动词（su 结尾，古语）",
  "Yodan verb with 'tsu' ending (archaic)": "四段动词（tsu 结尾，古语）",
  "adjectival nouns or quasi-adjectives (keiyodoshi)": "形容动词",
  "adjective (keiyoushi)": "形容词",
  "adjective (keiyoushi) - yoi/ii class": "形容词（yoi/ii 类）",
  "adverb (fukushi)": "副词",
  "adverb taking the 'to' particle": "副词（接「と」）",
  "archaic/formal form of na-adjective": "形容动词的古语/文语形",
  "auxiliary": "助动词",
  "auxiliary adjective": "辅助形容词",
  "auxiliary verb": "助动词",
  "conjunction": "连词",
  "copula": "系动词",
  "counter": "量词",
  "expressions (phrases, clauses, etc.)": "惯用表达（短语、从句等）",
  "interjection (kandoushi)": "感叹词",
  "intransitive verb": "自动词",
  "irregular nu verb": "不规则动词（ぬ）",
  "irregular ru verb, plain form ends with -ri": "不规则动词（ru，终止形以 -ri 结尾）",
  "noun (common) (futsuumeishi)": "名词（普通名词）",
  "noun or participle which takes the aux. verb suru": "名词/サ变动词（可接する）",
  "noun or verb acting prenominally": "连体修饰用法（名词或动词）",
  "noun, used as a prefix": "名词（作前缀）",
  "noun, used as a suffix": "名词（作后缀）",
  "nouns which may take the genitive case particle 'no'": "名词（可接「の」作定语）",
  "numeric": "数词",
  "particle": "助词",
  "pre-noun adjectival (rentaishi)": "连体词",
  "prefix": "前缀",
  "pronoun": "代词",
  "su verb - precursor to the modern suru": "サ变动词（现代する的前身）",
  "suffix": "后缀",
  "suru verb - included": "サ变动词",
  "suru verb - special class": "サ变动词（特殊类）",
  "transitive verb": "他动词",
  "unclassified": "未分类",
  "verb unspecified": "动词（未指定类别）",
};

/** 把 JMDict 英文词性串（「、」连接）翻译成中文；未知标签原样保留。 */
export function translatePos(pos) {
  if (!pos) return '';
  return pos
    .split('、')
    .map((tag) => POS_ZH[tag.trim()] || tag)
    .join('、');
}
